"""add columns

Revision ID: b67f2b8c0730
Revises: bf7af76aaaca
Create Date: 2026-01-27 12:40:11.499034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67f2b8c0730'
down_revision: Union[str, Sequence[str], None] = 'bf7af76aaaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_embeddings', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('uploaded_files', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('file_embeddings', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
