"""add columns

Revision ID: b78bbff17260
Revises: b67f2b8c0730
Create Date: 2026-01-27 12:42:46.812454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78bbff17260'
down_revision: Union[str, Sequence[str], None] = 'b67f2b8c0730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_embeddings', sa.Column('text_content', sa.Text(), nullable=True))
    op.drop_column('file_embeddings', 'raw_text')
    op.drop_column('uploaded_files', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('file_embeddings', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('file_embeddings', 'text_content')
    # ### end Alembic commands ###
