"""add columns

Revision ID: bf7af76aaaca
Revises: ef631af99ce9
Create Date: 2026-01-27 12:36:18.527561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7af76aaaca'
down_revision: Union[str, Sequence[str], None] = 'ef631af99ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'raw_text')
    op.drop_column('uploaded_files', 'source_type')
    # ### end Alembic commands ###
